services:
  waktfolio-backend:
    hostname: waktfolio-backend
    container_name: waktfolio-backend
    build: ./
    restart: unless-stopped
    ports:
      - 28081:8080
    environment:
      - TZ=Asia/Seoul
    command: java -jar /app.jar --spring.profiles.active=prod
    networks:
      - waktfolio-network
networks:
  waktfolio-network:
    external: true