services:
  waktfolio-backend:
    hostname: waktfolio-backend
    build: ./
    restart: unless-stopped
    ports:
      - 28081:8080
    environment:
      - TZ=Asia/Seoul
    command: java -jar /app.jar -Dspring.profiles.active=prod
    networks:
      - management-board-network
networks:
  management-board-network:
    external: true