spring:
  datasource:
    url: "jdbc:postgresql://waktfolio-db:5432/waktfolio"
    username: postgres
    password: "waktfolio!@"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
jwt:
  secret: "asdasd924nt0s89dfbhwalal238yDZ15A35saFdwfaj"
  validity : 360000
cloud:
  aws:
    url: "http://43.200.154.182:8000"
    s3:
      bucket: waktfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: accessKey1
      secretKey: verySecretKey1
server:
  port: 8080