spring:
  datasource:
    url: "jdbc:postgresql://43.200.154.182:55432/waktfolio"
    username: postgres
    password: "waktfolio!@"
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
jwt:
  secret: "asdasd924nt0s89dfbhwalal238yDZ15A35saFdwfaj"
  validity : 360000
server:
  port: 8081