spring:
  datasource:
    url: ENC(calqJAgxgWlDjPTS/PSMnJqa8HMYtgwSsDlhEz4LfNztH7Qbj8818O89JVXt8aQ4CoSy9phPdKI=)
    username: ENC(UM2C3IflAZKYbpptLnMEZD20O/w2PJZY)
    password: ENC(YA+ZiG5VG4/zcpzIAB4eVfnTDG1TCpSe)
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
jwt:
  secret: "asdasd924nt0s89dfbhwalal238yDZ15A35saFdwfaj"
  validity : 360000
cloud:
  aws:
    url: "http://3.37.62.124:8000"
    s3:
      bucket: waktfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: accessKey1
      secretKey: verySecretKey1
server:
  port: 8081