spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/waktfolio"
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
jwt:
  secret: "asdasd924nt0s89dfbhwalal238yDZ15A35saFdwfaj"
  validity : 360000
server:
  port: 8081